package Buoi2;

public class Main {
    public static void main(String[] args) {
        for(int i=0; i < 10; i++) {
            // i=0
            Singleton instance = Singleton.getInstance();
            ///Dung Singleton trong TH nao?
            /// Doc thong tin setup --> config
            /// Lam viec voi CSDL
            /// App --> Database --> read data --> App
            /// Thread, Task --> Da luong trong lap trinh
            /// 
            /// CSDL, HQTCSL
        }
    }
}